import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import NavMenu from './NavMenu'
import { theme } from '@/data/theme'
import AuthProvider from './AuthProvider'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en" data-theme={theme.light} className={poppins.className}>
        <body className='flex flex-col items-center'>
          <NavMenu />
          <div className='m-8 p-8 rounded-3xl h-full bg-base-200 shadow-md'>
            {children}
          </div>
        </body>
      </html>
    </AuthProvider>
  )
}
